---
name: base
dependencies:
    imports:
        - from setuptools import find_packages
        - from setuptools import setup
    features:
        - merge
properties:
    name: "\"mypackage\""
    version: "\"0.1.0\""
    packages: find_packages(exclude=['contrib', 'docs', 'test'])
